[markata]
assets_dir = "static"
icon = "8bitcc.png"
description = "Waylon Walker's Stable Diffusions"
url = "https://stable-diffusion.waylonwalker.com"
body_width='100vw'
edit=false


hooks = [
"markata.plugins.base_cli",
"markata.plugins.tui",
"markata.plugins.copy_assets",
"markata.plugins.feeds",
"markata.plugins.post_template",
"stable_diffusion_waylonwalker_com.load"
]

[[markata.head.text]]
value = """
<style>
img {
width: 100%;
height: auto;
}
ul {
  display: flex;
  flex-wrap: wrap;
}

li {
  flex: 1 2 400px;
}
</style>

"""

[markata.feeds.archive]
title="archive"
filter="True"
reverse="True"
card_template="""
<li class='post'>
    <a href='/{{ title.replace("png", "webp") }}'>
        <img src='/{{ title.replace("png", "webp") }}' height='{{ height }}' width='{{ width }}' alt='{{ prompt }}'>
    </a>
    <details>
        <summary> command </summary>
        {{ command }} 
    </details>
</li>
"""

[[markata.head.meta]]
name = "og:type"
content = "article"

[[markata.head.meta]]
name = "og:author"
content = "Waylon Walker"

[[markata.head.meta]]
name = "og:site_name"
content = "Waylon Walker"

[[markata.head.meta]]
name = "theme-color"
content="#322D39"

[[markata.head.meta]]
name = "twitter:creator"
content="@_waylonwalker"

[markata.prevnext]
prevnext_color_angle = "#ff66c4"
